spring:
  application:
    name: java-education
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cache:
   type: redis
  data:
    redis:
      host: localhost
      port: 6379
      time-to-live: 300000  # 5 минут (в мс)
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        cache:
#          use_second_level_cache: false  # Отключаем кеш Hibernate
com:
  javarush:
    questionsPath: src/main/resources/questions
    startAnswerPosition: 0
    startTopic: core
