spring:
  application:
    name: java-education
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cache:
   type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379
      time-to-live: 300000  # 5 минут (в мс)
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
com:
  javarush:
    questionsPath: ${COM_JAVARUSH_QUESTIONSPATH}
    startAnswerPosition: 0
    startTopic: core
