spring:
  application:
    name: java-education
  datasource:
    url: ${DATABASE_URL:postgresql://postgres:XoDAAoldFEoPqagDVzCeHDpiyWmfVvpj@tramway.proxy.rlwy.net:59100/railway}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: ${REDISHOST:redis.railway.internal}
      port: 6379
      time-to-live: 300000
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
com:
  javarush:
    questionsPath: ${COM_JAVARUSH_QUESTIONSPATH:/app/questions}
    startAnswerPosition: 0
    startTopic: core
